import { ClerkProvider } from "@clerk/nextjs";
import "../globals.css";
import Navbar from "components/shared/Navbar";
import Footer from "components/shared/Footer";
import { Poppins, Nunito_Sans } from "next/font/google";

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["500", "600", "700"],
  variable: "--font-poppins",
});

const nunito = Nunito_Sans({
  subsets: ["latin"],
  weight: ["500", "600", "700"],
  variable: "--font-nunito",
});

export const metadata = {
  title: "TekHub",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className={`${poppins.variable} ${nunito.variable} font-sans `}>
          {/* <Navbar /> */}
          {children}
          {/* <Footer /> */}
        </body>
      </html>
    </ClerkProvider>
  );
}
